# Generated by Django 4.2.30 on 2026-05-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "run_number",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("create_time", models.DateTimeField()),
                ("run_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "run",
            },
        ),
        migrations.CreateModel(
            name="RunTransitionCause",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "run_transition_cause",
            },
        ),
        migrations.CreateModel(
            name="RunTransitionType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "run_transition_type",
            },
        ),
        migrations.CreateModel(
            name="RunType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "run_type",
            },
        ),
        migrations.CreateModel(
            name="RunEndInfo",
            fields=[
                (
                    "run_number",
                    models.OneToOneField(
                        db_column="run_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="end_info",
                        serialize=False,
                        to="runs.run",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "run_end_info",
            },
        ),
        migrations.AddField(
            model_name="run",
            name="run_type_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="run_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="runs.runtype",
            ),
        ),
        migrations.CreateModel(
            name="Subrun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subrun", models.IntegerField()),
                ("n_events", models.BigIntegerField(blank=True, null=True)),
                ("n_on_spill", models.BigIntegerField(blank=True, null=True)),
                ("n_off_spill", models.BigIntegerField(blank=True, null=True)),
                ("n_null", models.BigIntegerField(blank=True, null=True)),
                ("min_ewt", models.BigIntegerField(blank=True, null=True)),
                ("max_ewt", models.BigIntegerField(blank=True, null=True)),
                ("start_time_unix", models.IntegerField(blank=True, null=True)),
                ("stop_time_unix", models.IntegerField(blank=True, null=True)),
                ("event_mode_counts", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_fk",
                    models.ForeignKey(
                        db_column="run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subruns",
                        to="runs.run",
                    ),
                ),
            ],
            options={
                "db_table": "subrun",
                "unique_together": {("run_fk", "subrun")},
            },
        ),
        migrations.CreateModel(
            name="RunTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transition_time", models.DateTimeField()),
                (
                    "cause_fk",
                    models.ForeignKey(
                        blank=True,
                        db_column="cause_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="runs.runtransitioncause",
                    ),
                ),
                (
                    "run_number",
                    models.ForeignKey(
                        db_column="run_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="runs.run",
                    ),
                ),
                (
                    "type_fk",
                    models.ForeignKey(
                        db_column="type_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="runs.runtransitiontype",
                    ),
                ),
            ],
            options={
                "db_table": "run_transition",
                "unique_together": {("run_number", "type_fk", "transition_time")},
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsystem", models.TextField()),
                ("config", models.JSONField()),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                (
                    "run_number",
                    models.ForeignKey(
                        db_column="run_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="runs.run",
                    ),
                ),
            ],
            options={
                "db_table": "config",
                "unique_together": {("run_number", "subsystem")},
            },
        ),
        migrations.CreateModel(
            name="ArtdaqFcl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "run_number",
                    models.ForeignKey(
                        db_column="run_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcl_documents",
                        to="runs.run",
                    ),
                ),
            ],
            options={
                "db_table": "artdaq_fcl",
                "unique_together": {("run_number", "name")},
            },
        ),
    ]
